// Generated by CoffeeScript 1.4.0
var app, port;

app = require('./.app');

port = app.port;

app.listen(port, '127.0.0.1', function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
